[package]
name = "redscript-capi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
redscript = { git = "https://github.com/jac3km4/redscript", rev = "8d3df9b" }
redscript-decompiler = { git = "https://github.com/jac3km4/redscript", rev = "8d3df9b" }
